name: Wiki build

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

permissions:
  contents: write
  pages: write

jobs:
  deploy:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install python tools
        uses: BrandonLWhite/pipx-install-action@v0.1.1

      - name: Install dependencies
        run: poetry install

      - name: Build website
        run: poetry run make html

      - name: Create /wiki folder
        run: mkdir ./_build/public && cp -r ./_build/html ./_build/public/wiki

      - name: Deploy website
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/public
